CREATE TABLE IF NOT EXISTS `login_information` (
  `id` BIGINT NOT NULL AUTO_INCREMENT
  , `user_name` VARCHAR(60) NOT NULL UNIQUE
  , `password` VARCHAR(256) DEFAULT NULL
  , `email` VARCHAR(60) DEFAULT NULL
  , `login_time` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY (`id`)
);